name: 'Setup tfclean'
description: 'Setup tfclean in your GitHub Actions workflow'
author: 'step-security'

inputs:
  version:
    description: 'The version of tfclean to install'
    required: false
    default: 'latest'

runs:
  using: "composite"
  steps:
    - name: Validate subscription
      shell: bash
      run: |
        # validate subscription status
        API_URL="https://agent.api.stepsecurity.io/v1/github/$GITHUB_REPOSITORY/actions/subscription"

        # Set a timeout for the curl command (3 seconds)
        RESPONSE=$(curl --max-time 3 -s -w "%{http_code}" "$API_URL" -o /dev/null) || true
        CURL_EXIT_CODE=$?

        # Decide based on curl exit code and HTTP status
        if [ $CURL_EXIT_CODE -ne 0 ]; then
          echo "Timeout or API not reachable. Continuing to next step."
        elif [ "$RESPONSE" = "200" ]; then
          :
        elif [ "$RESPONSE" = "403" ]; then
          echo "Subscription is not valid. Reach out to support@stepsecurity.io"
          exit 1
        else
          echo "Timeout or API not reachable. Continuing to next step."
        fi
        
    - name: Download tfclean
      shell: bash
      working-directory: /tmp
      run: |
        VERSION=${{ inputs.version }}
        if [ "$VERSION" = "latest" ]; then
          VERSION=$(curl -s https://api.github.com/repos/takaishi/tfclean/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        fi
        
        # Determine architecture
        ARCH=$(uname -m)
        case "$ARCH" in
          "x86_64")
            ARCH="x86_64"
            ;;
          "aarch64")
            ARCH="arm64"
            ;;
          *)
            echo "Unsupported architecture: $ARCH"
            exit 1
            ;;
        esac
        
        BINARY="tfclean_linux_${ARCH}"
        DOWNLOAD_URL="https://github.com/takaishi/tfclean/releases/download/${VERSION}/${BINARY}.tar.gz"
        CHECKSUMS_URL="https://github.com/takaishi/tfclean/releases/download/${VERSION}/checksums.txt"

        curl -sLO "$DOWNLOAD_URL"
        curl -sLO "$CHECKSUMS_URL"

        grep "${BINARY}.tar.gz" checksums.txt | sha256sum -c -

        tar xzf "${BINARY}.tar.gz"
        sudo mv tfclean /usr/local/bin/
        chmod +x /usr/local/bin/tfclean

    - name: Verify installation
      shell: bash
      run: tfclean --version

branding:
  icon: 'check-square'
  color: 'green'
